.\" Manpage for eocxap
.\"
.\" Copyright(c) 2018 Zachary Matthews.
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <https://www.gnu.org/licenses/>.

.TH EOCXAP 1 "27 Oktobro 2018" "0.1" "man paĝo de eocxap"
.SH NOMO
eocxap \- Rapide ĉapeliĝas tekso per la x-sistemo kaj h-sistemo
.SH RESUMO
.BR eocxap " [\fIAGORDO\fP]"
.SH PRISKRIBO
.B eocxap
estas programo, kiun oni povas ĉapeligi x-sisteman aŭ h-sisteman tekston.
.SH AGORDOJ
.TP
.BR \-a ", " \-\-alt ", " \-\-alia
Uzu alia kopii/alglui metodo(Ctrl/Shift+Insert)
.TP
.BR "" "    " \-\-en
Prezenti ĉiujn mesaĝojn angle
.TP
.BR "" "    " \-\-eo
Prezenti ĉiujn mesaĝojn Esperante
.TP
.BR "" "    " \-\-help ", " \-\-helpi
Prezenti la mesaĝon de helpo
.TP
.BR \-h ", " \-\-hsystem ", " \-\-hsistemo
Uzi h-sistemo por konverti
.TP
.BR \-i ", " \-\-inline "," \-\-enteksta
Redakti markan tekston en sama loko
.TP
.BR "" "    " \-\-silent "," \-\-silenta
Kaŝi ĉiujn mesaĝojn
.TP
.BR \-s ", " \-\-sleep "," \-\-halteto
Ŝanĝi la daŭro de halteto por enteksta reĝimo
.TP
.BR "" "    " \-\-version "," \-\-versio
Elmontri la versia informacio de eocxap
.SH ERAROJ
Ne konataj eraroj.
.SH AŬTORO
Zachary Matthews (zacharymatt5@gmail.com)
