.\" Manpage for eocxap
.\"
.\" Copyright(c) 2018 Zachary Matthews.
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <https://www.gnu.org/licenses/>.

.TH EOCXAP 1 "29 October 2018" "0.1" "eocxap man page"
.SH NAME
eocxap \- quickly add hats to characters using the x-system and h-system
.SH SYNOPSIS
.BR eocxap " [\fIOPTION\fP]"
.SH DESCRIPTION
.B eocxap
is a program, which is used to convert x-system text and h-system text to normal text.
.SH OPTIONS
.TP
.BR \-a ", " \-\-alt ", " \-\-alia
Use alternate copy/paste(Ctrl/Shift+Insert)
.TP
.BR "" "    " \-\-en
Display all messages in English
.TP
.BR "" "    " \-\-eo
Display all messages in Esperanto
.TP
.BR "" "    " \-\-help ", " \-\-helpi
Display the help message
.TP
.BR \-h ", " \-\-hsystem ", " \-\-hsistemo
Use h-system for conversion
.TP
.BR \-i ", " \-\-inline "," \-\-enteksta
Edit highlighted text in place
.TP
.BR "" "    " \-\-silent "," \-\-silenta
Supress all messages
.TP
.BR \-s ", " \-\-sleep "," \-\-halteto
Set the sleep timer when using inlne
.TP
.BR "" "    " \-\-version "," \-\-versio
Show the version information for eocxap
.TP
.BR \-w
Use w instead of ux when using the X-system
.SH BUGS
No known bugs.
.SH AUTHOR
Zachary Matthews (zacharymatt5@gmail.com)
